FROM nvidia/cudagl:9.0-runtime-ubuntu16.04
LABEL maintainer="Andrew Dornbush <andrew.dornbush@gmail.com>"

# TODO: install apt-utils?

RUN apt-get update
RUN apt-get -y install lsb-release

# Configure ROS Kinetic Repositories
RUN echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list
RUN apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
RUN apt-get update

# Install basic utilities
RUN apt-get install -y sudo
RUN apt-get install -y git
RUN apt-get install -y vim
RUN apt-get install -y screen

# Install ROS
RUN apt-get -y install ros-kinetic-desktop

# Extra stuff that should probably be worked out using rosdep
RUN apt-get install -y libqwt-dev

# Install catkin build tool
RUN apt-get -y install python-catkin-tools

# Initialize rosdep
RUN rosdep init

# Create rcta user
RUN adduser --disabled-password --gecos '' rcta
RUN adduser rcta sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

ENV HOME /home/rcta
WORKDIR /home/rcta
USER rcta

# Update rosdep repositories
RUN rosdep update

# clone, configure, build, and install sbpl source dependency
RUN git clone https://github.com/sbpl/sbpl.git && cd sbpl && mkdir build && cd build && cmake .. && make && sudo make install

COPY --chown=rcta rcta_ws/src /home/rcta/rcta_ws/src
RUN bash -c 'source /opt/ros/kinetic/setup.bash && rosdep install -i -y --from-paths /home/rcta/rcta_ws/src'

RUN echo "source ~/rcta_ws/devel/setup.bash" >> /home/rcta/.bashrc

LABEL com.nvidia.volumes.needed="nvidia_driver"
ENV PATH /usr/local/nvidia/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}

RUN sudo apt install -y net-tools gdb iputils-ping mesa-utils

CMD ["bash"]
